Added die function for better error handling/reporting

diff --git a/scripts/mratlpreproc b/scripts/mratlpreproc
--- a/scripts/mratlpreproc
+++ b/scripts/mratlpreproc
@@ -20,12 +20,21 @@
 #									       #
 ################################################################################
 # Yi Su, 01/31/2014
+VERSION=1.1
 
-idstr='$Id: mratlpreproc,v 1.1 Mon Feb  3 09:46:46 CST 2014 suy $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:46:46 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -44,7 +53,7 @@ source $paramsfn
 ###############################################################################
 # Populate files
 
-dcm_to_4dfp -b ${mrid}S $mrdir/$mrfn
+dcm_to_4dfp -b ${mrid}S $mrdir/$mrfn || die "$program ERROR: DICOM to 4dfp conversion failed"
 
 # The MR is typically MPRAGE data acquired sagitally, will convert to
 # transverse first.
@@ -58,13 +67,14 @@ then
 	done
 elif (( ori == 3 ))
 then
-	C2T_4dfp ${mrid}S ${mrid}
+	C2T_4dfp ${mrid}S ${mrid} || die "$program ERROR: C2T_4dfp ${mrid}S ${mrid} failed"
 elif (( ori == 4 ))
 then
-	S2T_4dfp ${mrid}S ${mrid}
+	S2T_4dfp ${mrid}S ${mrid} || die "$program ERROR: S2T_4dfp ${mrid}S ${mrid} failed"
 else
-	echo "ERROR mratlpreproc: Wrong Orientation FLAG"
-	exit -1
+	ERR="ERROR mratlpreproc: Wrong Orientation FLAG"
+	echo $ERR
+	die $program $ERR
 fi
 rm ${mrid}S.4dfp.*
 
@@ -73,10 +83,10 @@ cp $roidir/${roilist} .
 
 ###############################################################################
 # atlas registration
-mpr2atl_4dfp $mrid -T$atlpath/$atltarg
+mpr2atl_4dfp $mrid -T$atlpath/$atltarg || die "$program ERROR: atlas registration failed"
 
 # generate brainmask
-msktgen_4dfp $mrid -T$atlpath/$atltarg
+msktgen_4dfp $mrid -T$atlpath/$atltarg || die "$program ERROR: brainmask generation failed"
 
 # populate maskfile parameter in the params file for further processing
 echo "maskfile=${mrid}_mskt.4dfp.img" >> $paramsfn
diff --git a/scripts/pet2petatl b/scripts/pet2petatl
--- a/scripts/pet2petatl
+++ b/scripts/pet2petatl
@@ -1,12 +1,24 @@
 #!/bin/bash
 ################################################################################
-# This program registers 4dfp pet image to a population based pet atlas	       #     
+# This program registers 4dfp pet image to a population based pet atlas	       #
 ################################################################################
-# Yi Su, 2013/07/05                                                            
+# Yi Su, 2013/07/05
+VERSION=1.0
 
-idstr='$Id: pet2petatl,v 1.0 Fri Jan 31 09:38:42 CST 2014 suy $'
-echo $idstr
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
+
+die(){
+    echo >&2 "$@"
+    exit -1
+}
+
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:38:42 CST 2014 suy $'
+echo $idstr
+
 if [ $# -lt 2 ]
 then
 	echo "Usage: $program atlas movimg"
@@ -19,7 +31,7 @@ then
 	echo "	     default is no mask)"
 	echo "	-mb fwhm (blur moving image with fwhm in mm (default 3))"
 	exit -1
-fi	
+fi
 
 ################################
 # setting default parameters
@@ -52,43 +64,37 @@ while [ $# -gt 0 ]; do
 	  * )
 	    rmsk=$2
 	    shift
-	    if [ ! -f $rmsk ]; then
-	       echo "Error: Mask file doesn't exist!"
-	       exit -1
-	    fi
+	    test -f $rmsk || die "$program ERROR: Mask file doesn't exist!"
 	    grm=0
 	    ;;
-	esac   	       
+	esac
       fi
       ;;
-     -mb)   
+     -mb)
        if [ -n "$2" ]
        then
          case "$2" in
 	   -*)
-	     echo "Error: -mb must be followed with a number"
-	     exit -1
+	     die "$program ERROR: -mb must be followed with a number"
 	     ;;
 	   [0-9]*)
 	     mb=$2
 	     shift
 	     ;;
-	   *)     
-	     echo "Error: -mb must be followed with a number"
-	     exit -1
+	   *)
+	     die "$program ERROR: -mb must be followed with a number"
 	     ;;
-	 esac  
+	 esac
        fi
        ;;
      -*)
-      echo "Unrecognized options for pet2petatl"
-      exit -1
-      ;;  
+      die "$program ERROR: Unrecognized options for pet2petatl"
+      ;;
      *)
       atlas=$1
       movimg=$2
       shift
-      ;;  
+      ;;
   esac
   shift
 done
@@ -99,17 +105,15 @@ then
     refname=`basename $atlas`
     refroot=${refname%%.*}
 else
-    echo "$program: Missing atlas"
-    exit -1
-fi        
+    die "$program ERROR: Missing atlas"
+fi
 if [ -n "$movimg" ]
 then
     movdir=`dirname $movimg`
     movname=`basename $movimg`
     movroot=${movname%%.*}
 else
-    echo "$program: Missing movimg"
-    exit -1
+    die "$program ERROR: Missing movimg"
 fi
 
 echo refroot: $refroot
@@ -119,34 +123,34 @@ echo mb=$mb
 echo rmf=$rmf
 echo mm=$mm
 
-imgblur_4dfp $movimg $mb
+imgblur_4dfp $movimg $mb || die "$program ERROR: imgblur_4dfp $movimg $mb failed"
 mbx=`echo $mb | awk '{print 10*$1}'`
 
 if [ "$rmf" -eq 1 ] && [ "$grm" -eq 1 ]
 then
-    maskimg_4dfp ${atlas} ${atlas} -t.5 ${refroot}"_msk" -v1
+    maskimg_4dfp ${atlas} ${atlas} -t.5 ${refroot}"_msk" -v1 || die "$program ERROR: maskimg_4dfp ${atlas} ${atlas} -t.5 ${refroot}"_msk" -v1 failed"
     nsl=`gawk '/matrix size \[3\]/ {print $NF}' ${refdir}/${refroot}".4dfp.ifh"`
     msl=3
-    zero_slice_4dfp ${refroot}"_msk" z 1 $msl  ${refroot}"_mskz"
+    zero_slice_4dfp ${refroot}"_msk" z 1 $msl  ${refroot}"_mskz" || die "$program ERROR: zero_slice_4dfp ${refroot}"_msk" z 1 $msl  ${refroot}"_mskz" failed"
     k=$((nsl-msl+1))
-    zero_slice_4dfp ${refroot}"_mskz" z $k $nsl ${refroot}"_msk"
+    zero_slice_4dfp ${refroot}"_mskz" z $k $nsl ${refroot}"_msk" || die "$program ERROR: zero_slice_4dfp ${refroot}"_mskz" z $k $nsl ${refroot}"_msk" failed"
     rmsk=${refroot}"_msk"
 fi
 
 if [ "$mm" -eq 1 ]
 then
-    maskimg_4dfp ${movroot}"_b"${mbx} ${movroot}"_b"${mbx} -t.5 ${movroot}"_msk" -v1
+    maskimg_4dfp ${movroot}"_b"${mbx} ${movroot}"_b"${mbx} -t.5 ${movroot}"_msk" -v1 || die "$program ERROR: maskimg_4dfp ${movroot}"_b"${mbx} ${movroot}"_b"${mbx} -t.5 ${movroot}"_msk" -v1 failed"
     nsl=`gawk '/matrix size \[3\]/ {print $NF}' ${movroot}".4dfp.ifh"`
     msl=3
-    zero_slice_4dfp ${movroot}"_msk" z 1 $msl  ${movroot}"_mskz"
+    zero_slice_4dfp ${movroot}"_msk" z 1 $msl  ${movroot}"_mskz" || die "$program ERROR: zero_slice_4dfp ${movroot}"_msk" z 1 $msl  ${movroot}"_mskz" failed"
     k=$((nsl-msl+1))
-    zero_slice_4dfp ${movroot}"_mskz" z $k $nsl ${movroot}"_msk"
+    zero_slice_4dfp ${movroot}"_mskz" z $k $nsl ${movroot}"_msk" || die "$program ERROR: zero_slice_4dfp ${movroot}"_mskz" z $k $nsl ${movroot}"_msk" failed"
     mmsk=${movroot}"_msk"
 fi
 
 echo rmsk=$rmsk
 echo mmsk=$mmsk
- 
+
 
 modes=( 1283 1283 3335 2311 2311 )
 
@@ -167,11 +171,11 @@ if [ ! -e $t4file1 ]
 then
 	ori=`awk '/orientation/{print $NF - 1}' ${refdir}/${refroot}".4dfp.ifh"`
 	ori=$((ori-1))
-	t4_inv ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4"
+	t4_inv ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" || die "$program ERROR: t4_inv failed"
 	ori=`awk '/orientation/{print $NF - 1}' ${movdir}/${movroot}".4dfp.ifh"`
 	ori=$((ori-1))
-	t4_mul ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" $t4file1
-	rm temp$$_t4			
+	t4_mul ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" $t4file1 || die "$program ERROR: t4_mul failed"
+	rm temp$$_t4
 fi
 
 
@@ -185,7 +189,7 @@ do
     echo >> $log
     echo imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode
     echo imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode >> $log
-         imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode >> $log
+         imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode >> $log || die "$program ERROR: imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode failed"
 done
 
 
diff --git a/scripts/petmdlsum b/scripts/petmdlsum
--- a/scripts/petmdlsum
+++ b/scripts/petmdlsum
@@ -18,12 +18,21 @@
 #									       #
 ################################################################################
 # Yi Su, 01/07/2014
+VERSION=1.0
 
-idstr='$Id: petmdlsum,v 1.0 2014/01/07 18:07:48 suy Exp $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' 2014/01/07 18:07:48 suy Exp $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -40,7 +49,7 @@ source $paramsfn
 # the inputs specified in the params file
 
 # Sum PET frames
-sum_pet_4dfp ${petid}_moco $sf $ef -d -h${half_life} ${petid}_msum
+sum_pet_4dfp ${petid}_moco $sf $ef -d -h${half_life} ${petid}_msum || die "$program ERROR: sum_pet_4dfp ${petid}_moco $sf $ef -d -h${half_life} ${petid}_msum failed"
 
 # Processing info file
 st=`gawk 'NR=='$sf' {print $1}' ${petid}.info`
diff --git a/scripts/petpreproc b/scripts/petpreproc
--- a/scripts/petpreproc
+++ b/scripts/petpreproc
@@ -23,12 +23,21 @@
 # contains the frame timing and decay correction info.                         #
 ################################################################################
 # Yi Su, 11/05/2013
+VERSION=1.0
 
-idstr='$Id: petpreproc,v 1.0 Fri Jan 31 09:39:08 CST 2014 suy $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:39:08 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -47,17 +56,17 @@ source $paramsfn
 # File conversion
 if (( $format == 0 ))
 then
-	dcm_pet -m -a  -b $petid $petdir/$petfn
+	dcm_pet -m -a  -b $petid $petdir/$petfn || die "$program ERROR: dcm_pet -m -a  -b $petid $petdir/$petfn failed"
 elif (( $format == 1 ))
 then
-	ecatto4dfp $petdir/$petfn $petid
+	ecatto4dfp $petdir/$petfn $petid || die "$program ERROR: ecatto4dfp $petdir/$petfn $petid failed"
 elif (( $format == 2 ))
 then
-	sif_4dfp $petdir/$petfn $petid
+	sif_4dfp $petdir/$petfn $petid || die "$program ERROR: sif_4dfp $petdir/$petfn $petid failed"
 fi
 
 # Generate .info file
-PETinfo $petid $format $delay
+PETinfo $petid $format $delay || die "$program ERROR: PETinfo $petid $format $delay failed"
 
 # Filtering if requested
 if [ -n "$filterxy" ] && [ -n "$filterz" ]
@@ -68,8 +77,8 @@ then
 		filterxyname=${tmp%.*}
 		tmp=$(echo "scale=6; $filterz*10+.499999" | bc)
 		filterzname=${tmp%.*}
-		imgblur_4dfp -xy $petid $filterxy
-		imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz
+		imgblur_4dfp -xy $petid $filterxy || die "$program ERROR: imgblur_4dfp -xy $petid $filterxy failed"
+		imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz || die "$program ERROR: imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz failed"
 
 		ext=( img img.rec ifh hdr )
 		for (( i=0; i<4; i++ ))
@@ -81,7 +90,7 @@ then
 	else
 		tmp=$(echo "scale=6; $filterxy*10+.499999" | bc)
 		filtername=${tmp%.*}
-		imgblur_4dfp ${petid} $filterxy
+		imgblur_4dfp ${petid} $filterxy || die "$program ERROR: imgblur_4dfp ${petid} $filterxy failed"
 		ext=( img img.rec ifh hdr )
 		for (( i=0; i<4; i++ ))
 		do
@@ -94,8 +103,9 @@ then
 	echo "petid=${petid}" >> $paramsfn
 elif [ -n "$filterxy" ] || [  -n "$filterz" ]
 then
-	echo "Both xy and z filter size are needed!"
-	exit -1
+	ERR="Both xy and z filter size are needed!"
+	echo $ERR
+	die "$program ERROR: $ERR"
 fi
 
 
diff --git a/scripts/petproc b/scripts/petproc
--- a/scripts/petproc
+++ b/scripts/petproc
@@ -8,12 +8,20 @@
 # This script reads a params file for PET processing                           #
 ################################################################################
 # Yi Su, 01/08/2014
+VERSION=1.0
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-idstr='$Id: petproc,v 1.0 Fri Jan 31 09:41:55 CST 2014 suy $'
-
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:41:55 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -36,39 +44,19 @@ cd pet_proc
 
 ###############################################################################
 # PET file conversion
-petpreproc $paramsfn
-if [ "$?" -ne "0" ]
-then
-	echo "PET file conversion ERROR!"
-	exit -1
-fi
+petpreproc $paramsfn || die "$program ERROR: PET file conversion failed"
 
 ###############################################################################
 # PET motion correction
-petmoco $paramsfn
-if [ "$?" -ne "0" ]
-then
-	echo "PET motion correction ERROR!"
-	exit -1
-fi
+petmoco $paramsfn || die "$program ERROR: PET motion correction failed"
 
 ###############################################################################
 # ROI target preprocessing
-targpreproc $paramsfn
-if [ "$?" -ne "0" ]
-then
-	echo "ROI target preprocessing ERROR!"
-	exit -1
-fi
+targpreproc $paramsfn || die "$program ERROR: ROI target preprocessing failed"
 
 ###############################################################################
 # PET to target space registration
-petreg $paramsfn
-if [ "$?" -ne "0" ]
-then
-	echo "PET to target registration ERROR!"
-	exit -1
-fi
+petreg $paramsfn || die "$program ERROR: PET to target registration failed"
 
 ###############################################################################
 #				Start Modeling				      #
@@ -76,45 +64,21 @@ fi
 
 ###############################################################################
 # Determine model frames
-petmdlframes $paramsfn
-if [ "$?" -ne "0" ]
-then
-	echo "Model Frames ERROR!"
-	exit -1
-fi
-
+petmdlframes $paramsfn || die "$program ERROR: Model Frames failed"
 
 ###############################################################################
 # Full Kinetic Processing
 
 # ROI TAC extraction
-petroitac $paramsfn
-if [ "$?" -ne "0" ]
-then
-	echo "ROI TAC extraction ERROR!"
-	exit -1
-fi
+petroitac $paramsfn || die "$program ERROR: ROI TAC extraction failed"
 
 # Logan Reference Region Analysis
 if [ "$model" = "logan" ]
 then
-	petrefroi $paramsfn
-	refstat=$?
-	if [ "$refstat" -eq "0" ]
-	then
-		petroiloganREF $paramsfn
-		loganstat=$?
-		if [ "$loganstat" -eq "0" ]
-		then
-			petloganrep $paramsfn
-		else
-			echo "Logan Reference Region Analysis Failure!"
-		fi
-	else
-		echo " REF TAC extraction ERROR!"		
-	fi
+	petrefroi $paramsfn || die "$program ERROR: REF TAC extraction failed"
+	petroiloganREF $paramsfn || die "$program ERROR: Logan Reference Region Analysis failed"
+	petloganrep $paramsfn || die "$program ERROR: petloganrep failed"
 fi
-
 # Additional analysis will be implemented in the future
 
 ###############################################################################
@@ -122,20 +86,10 @@ fi
 
 if [ "$suvr" = "1" ]
 then
-	petmdlsum $paramsfn
-	petroiint $paramsfn
-	if [ "$?" -eq "0" ]
-	then
-		petrefroi $paramsfn
-		petsuvr $paramsfn	
-		if [ "$?" -eq "0" ]
-		then
-			petsuvrrep $paramsfn
-		else
-			echo "SUVR Analysis Failure!"
-		fi
-	else
-		echo " Static ROI intensity extraction ERROR!"		
-	fi
+	petmdlsum $paramsfn || die "$program ERROR: petmdlsum failed"
+	petroiint $paramsfn || die "$program ERROR: Static ROI intensity extraction failed"
+	petrefroi $paramsfn || die "$program ERROR: petrefroi failed"
+	petsuvr $paramsfn || die "$program ERROR: SUVR Analysis failed"
+	petsuvrrep $paramsfn || die "$program ERROR: SUVR Analysis failed"
 fi
 
diff --git a/scripts/petreg b/scripts/petreg
--- a/scripts/petreg
+++ b/scripts/petreg
@@ -39,12 +39,21 @@
 # The output of this program is the t4 files for the registration	       #
 ################################################################################
 # Yi Su, 11/05/2013
+VERSION=1.0
 
-idstr='$Id: petreg,v 1.0 Fri Jan 31 09:40:42 CST 2014 suy $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:40:42 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -64,13 +73,13 @@ source $paramsfn
 # Perform registration
 if (( tgflag == 1 ))
 then
-	pet2petatl $refimg ${petid}_sumall $rmf $maskfile $mmf $mbf $modf
-else 
+	pet2petatl $refimg ${petid}_sumall $rmf $maskfile $mmf $mbf $modf || die "$program ERROR: pet2petatl $refimg ${petid}_sumall $rmf $maskfile $mmf $mbf $modf failed"
+else
 	if [ -n "$rmf" ] && [ -n "$maskfile" ]
 	then
-		reg2img $refimg ${petid}_sumall $rmf $maskfile $mmf $rbf $mbf $modf
+		reg2img $refimg ${petid}_sumall $rmf $maskfile $mmf $rbf $mbf $modf || die "$program ERROR: reg2img $refimg ${petid}_sumall $rmf $maskfile $mmf $rbf $mbf $modf failed"
 	else
-		reg2img $refimg ${petid}_sumall $rmf $mmf $rbf $mbf $modf
+		reg2img $refimg ${petid}_sumall $rmf $mmf $rbf $mbf $modf || die "$program ERROR: reg2img $refimg ${petid}_sumall $rmf $mmf $rbf $mbf $modf failed"
 	fi
 
 	regerr=`gawk '/ERROR =/{print $3}' ${refimg}_${petid}_sumall_reg2img_resolve.log`
@@ -82,23 +91,24 @@ else
 		rm ${petid}_sumall_to_${refimg}_t4
 		rm ${refimg}_to_${petid}_sumall_t4
 		rm ${refimg}_${petid}_sumall_reg2img_resolve.log
-	
+
 		# registration without masking
-		reg2img $refimg ${petid}_sumall $rbf $mbf $modf
+		reg2img $refimg ${petid}_sumall $rbf $mbf $modf || die "$program ERROR: reg2img $refimg ${petid}_sumall $rbf $mbf $modf failed"
 		regerr=`gawk '/ERROR =/{print $3}' ${refimg}_${petid}_sumall_reg2img_resolve.log`
 	fi
 	if (( $regerr > $tolreg ))
 	then
 		echo "ERROR: PETREG Failure. Abort!"
+		echo "ERROR: PETREG Failure. Abort!" >&2
 		exit 3
 	fi
 fi
 
 if (( tgflag == 2 ))
 then
-	t4_mul ${petid}_sumall_to_${refimg}_t4 $atlt4 ${petid}_to_roi_t4
+	t4_mul ${petid}_sumall_to_${refimg}_t4 $atlt4 ${petid}_to_roi_t4 || die "$program ERROR: t4_mul ${petid}_sumall_to_${refimg}_t4 $atlt4 ${petid}_to_roi_t4 failed"
 else
-	cp ${petid}_sumall_to_${refimg}_t4 ${petid}_to_roi_t4 
+	cp ${petid}_sumall_to_${refimg}_t4 ${petid}_to_roi_t4  || die "$program ERROR: cp ${petid}_sumall_to_${refimg}_t4 ${petid}_to_roi_t4  failed"
 fi
 
 
@@ -106,12 +116,9 @@ fi
 ###############################################################################
 # Generating PET field of view converage in roi space PETFOV.4dfp.img
 
-t4img_4dfp ${petid}_to_roi_t4 petfov temp$$ -O$roiimg
-maskimg_4dfp -R -v1 -t.99 temp$$ temp$$ PETFOV
+t4img_4dfp ${petid}_to_roi_t4 petfov temp$$ -O$roiimg || die "$program ERROR: t4img_4dfp ${petid}_to_roi_t4 petfov temp$$ -O$roiimg failed"
+maskimg_4dfp -R -v1 -t.99 temp$$ temp$$ PETFOV || die "$program ERROR: maskimg_4dfp -R -v1 -t.99 temp$$ temp$$ PETFOV failed"
 rm temp$$.4dfp.*
 
 echo "pet2roit4=${petid}_to_roi_t4" >> $paramsfn
-
-exit 0
-
 
diff --git a/scripts/petroiint b/scripts/petroiint
--- a/scripts/petroiint
+++ b/scripts/petroiint
@@ -23,12 +23,21 @@
 # The output of this program is a series of TAC curves			       #
 ################################################################################
 # Yi Su, 01/07/2014
+VERSION=1.0
 
-idstr='$Id: petroiint,v 1.0 Fri Jan 31 09:40:16 CST 2014 suy $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:40:16 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -50,7 +59,7 @@ if (( rsfflag == 1 ))
 then
 	if [ ! -e RSFMat.dat ]
 	then
-		calrsfmat $roiimg $roilist RSFMat.dat $fwhm
+		calrsfmat $roiimg $roilist RSFMat.dat $fwhm || die "$program ERROR: calrsfmat $roiimg $roilist RSFMat.dat $fwhm failed"
 	fi
 fi
 
@@ -60,22 +69,22 @@ if (( pvc2cflag == 1 ))
 then
 	if [ ! -e pvc2c.txt ]
 	then
-		imgblur_4dfp BrainMask $fwhm
+		imgblur_4dfp BrainMask $fwhm || die "$program ERROR: imgblur_4dfp BrainMask $fwhm failed"
 		bx=`echo $fwhm | awk '{print 10*$1}'`
 		bstr="_b"$bx
-		roieval3 BrainMask${bstr} $roiimg PETFOV $roilist $NROI pvc2c 0
+		roieval3 BrainMask${bstr} $roiimg PETFOV $roilist $NROI pvc2c 0 || die "$program ERROR: roieval3 BrainMask${bstr} $roiimg PETFOV $roilist $NROI pvc2c 0 failed"
 		mv pvc2c_ROI2_f0 pvc2c.txt
 	fi
 fi
 
 ###############################################################################
 # Perform ROI analysis
-t4img_4dfp $pet2roit4 $petid ${petid}_on_roi -O${roiimg}
+t4img_4dfp $pet2roit4 $petid ${petid}_on_roi -O${roiimg} || die "$program ERROR: t4img_4dfp $pet2roit4 $petid ${petid}_on_roi -O${roiimg} failed"
 if (( rsfflag == 1 ))
 then
-	rsfroieval2 ${petid}"_on_roi" $roiimg RSFMat.dat PETFOV $roilist $NROI 10 ${petid} 1
+	rsfroieval2 ${petid}"_on_roi" $roiimg RSFMat.dat PETFOV $roilist $NROI 10 ${petid} 1 || die "$program ERROR: rsfroieval2 ${petid}_on_roi $roiimg RSFMat.dat PETFOV $roilist $NROI 10 ${petid} 1 failed"
 else
-	roieval3 ${petid}"_on_roi" $roiimg PETFOV $roilist $NROI ${petid} 1
+	roieval3 ${petid}"_on_roi" $roiimg PETFOV $roilist $NROI ${petid} 1 || die "$program ERROR: roieval3 ${petid}_on_roi $roiimg PETFOV $roilist $NROI ${petid} 1 failed"
 fi
 
 
@@ -83,13 +92,13 @@ fi
 # Generate ROI Files
 for (( i=1; i<=NROI; i++ ))
 do
-	(( l = i + 1 )) 
+	(( l = i + 1 ))
 	label=`gawk 'NR=='$i' {print $1}' $roilist`
 	echo "label = ${label}"
 	tacfn=${petid}_${label}.tac
 	rsftacfn=${petid}_${label}_RSF.tac
 	pvc2ctacfn=${petid}_${label}_PVC2C.tac
-	
+
 	NVOX=`gawk 'NR=='$l' {print $2}' ${petid}_ROI2_f1`
 	printf "%9s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(s)" "Duration_(s)"  "Mean" "NVoxels=" $NVOX > $tacfn
 	if (( rsfflag == 1 ))
@@ -100,7 +109,7 @@ do
 	then
 		printf "%9s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(s)" "Duration_(s)"  "Mean"  "NVoxels=" $NVOX > $pvc2ctacfn
 	fi
-	
+
 	framefn=${petid}"_ROI2_f1"
 	rsffn=${petid}"_RSF_ROI2_f1"
 	ts=`gawk 'NR==1 {print $1}'  ${petid}".info"`
@@ -108,15 +117,15 @@ do
 	meanroi=`gawk 'NR=='$l' {print $3}' $framefn`
 	printf "%9d %15f %15f %15f\n" 1 $ts $td $meanroi >> $tacfn
 	if (( rsfflag == 1 ))
-	then		
+	then
 		meanroirsf=`gawk 'NR=='$l' {print $3}' $rsffn`
 		printf "%9d %15f %15f %15f\n" 1 $ts $td $meanroirsf >> $rsftacfn
 	fi
 
 	if (( pvc2cflag == 1 ))
 	then
-		cf=`gawk '/'$label'/ {print $3}' pvc2c.txt`		
-		meanroipvc2c=$(echo "scale=8; $meanroi/($cf+0.00001)" | bc) 
+		cf=`gawk '/'$label'/ {print $3}' pvc2c.txt`
+		meanroipvc2c=$(echo "scale=8; $meanroi/($cf+0.00001)" | bc)
 		printf "%9d %15f %15f %15f\n" 1 $ts $td $meanroipvc2c >> $pvc2ctacfn
 	fi
 
diff --git a/scripts/petroiloganREF b/scripts/petroiloganREF
--- a/scripts/petroiloganREF
+++ b/scripts/petroiloganREF
@@ -19,12 +19,21 @@
 # The output of this program is binding potentials for each ROI		       #
 ################################################################################
 # Yi Su, 01/03/2014
+VERSION=1.1
 
-idstr='$Id: petroiloganREF,v 1.1 Mon Feb  3 09:46:15 CST 2014 suy $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:46:15 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -46,13 +55,13 @@ NROI=`wc -l $roilist | gawk '{print $1}'`
 for (( i=1; i<=$NROI; i++ ))
 do
 	label=`gawk 'NR=='$i' {print $1}' $roilist`
-	loganREFROI ${petid}_REF.tac ${petid}_${label}.tac ${label} $k2 $sf $ef ${petid}_${label}.mdl
+	loganREFROI ${petid}_REF.tac ${petid}_${label}.tac ${label} $k2 $sf $ef ${petid}_${label}.mdl || die "$program ERROR: loganREFROI ${petid}_REF.tac ${petid}_${label}.tac ${label} $k2 $sf $ef ${petid}_${label}.mdl failed"
 	if (( rsfflag == 1 ))
 	then
-		loganREFROI ${petid}_REF_RSF.tac ${petid}_${label}_RSF.tac ${label} $k2 $sf $ef ${petid}_${label}_RSF.mdl
+		loganREFROI ${petid}_REF_RSF.tac ${petid}_${label}_RSF.tac ${label} $k2 $sf $ef ${petid}_${label}_RSF.mdl || die "$program ERROR: loganREFROI ${petid}_REF_RSF.tac ${petid}_${label}_RSF.tac ${label} $k2 $sf $ef ${petid}_${label}_RSF.mdl failed"
 	fi
 	if (( pvc2cflag == 1 ))
 	then
-		loganREFROI ${petid}_REF_PVC2C.tac ${petid}_${label}_PVC2C.tac ${label} $k2 $sf $ef ${petid}_${label}_PVC2C.mdl
+		loganREFROI ${petid}_REF_PVC2C.tac ${petid}_${label}_PVC2C.tac ${label} $k2 $sf $ef ${petid}_${label}_PVC2C.mdl || die "$program ERROR: loganREFROI ${petid}_REF_PVC2C.tac ${petid}_${label}_PVC2C.tac ${label} $k2 $sf $ef ${petid}_${label}_PVC2C.mdl failed"
 	fi
 done
diff --git a/scripts/petsuvrrep b/scripts/petsuvrrep
--- a/scripts/petsuvrrep
+++ b/scripts/petsuvrrep
@@ -7,12 +7,21 @@
 #                                                                              #
 ################################################################################
 # Yi Su, 01/08/2014
+VERSION=1.1
 
-idstr='$Id: petsuvrrep,v 1.1 Mon Feb  3 09:46:28 CST 2014 suy $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Mon Feb  3 09:46:28 CST 2014 suy $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -31,15 +40,15 @@ source $paramsfn
 ###############################################################################
 if (( FS == 1 ))
 then
-	fssuvrsum $petid $roisfn .suvr .txt
+	fssuvrsum $petid $roisfn .suvr .txt || die "$program ERROR: fssuvrsum $petid $roisfn .suvr .txt failed"
 	if (( rsfflag == 1 ))
 	then
-		fssuvrsum $petid $roisfn _RSF.suvr _RSF.txt
+		fssuvrsum $petid $roisfn _RSF.suvr _RSF.txt || die "$program ERROR: fssuvrsum $petid $roisfn _RSF.suvr _RSF.txt failed"
 	fi
 	if (( pvc2cflag == 1 ))
 	then
-		fssuvrsum $petid $roisfn _PVC2C.suvr _PVC2C.txt
-	fi	
+		fssuvrsum $petid $roisfn _PVC2C.suvr _PVC2C.txt || die "$program ERROR: fssuvrsum $petid $roisfn _PVC2C.suvr _PVC2C.txt failed"
+	fi
 fi
 
 
@@ -48,13 +57,11 @@ fi
 
 if (( tgflag == 1 ))
 then
-	petatlsuvrsum $petid $roilist .suvr .txt
+	petatlsuvrsum $petid $roilist .suvr .txt || die "$program ERROR: petatlsuvrsum $petid $roilist .suvr .txt failed"
 fi
 
 if (( tgflag == 2 ))
 then
-	petatlsuvrsum $petid $roilist .suvr .txt
+	petatlsuvrsum $petid $roilist .suvr .txt || die "$program ERROR: petatlsuvrsum $petid $roilist .suvr .txt failed"
 fi
 ###############################################################################
-
-exit $?
diff --git a/scripts/preprocfs b/scripts/preprocfs
--- a/scripts/preprocfs
+++ b/scripts/preprocfs
@@ -23,12 +23,21 @@
 # The output of this program is a series of TAC curves			       #
 ################################################################################
 # Yi Su, 12/24/2013
+VERSION=1.0
 
-idstr='$Id: fspreproc,v 1.0 2013/12/24 18:07:48 suy Exp $'
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
 
-echo $idstr
+die(){
+    echo >&2 "$@"
+    exit -1
+}
 
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' 2013/12/24 18:07:48 suy Exp $'
+echo $idstr
 
 if [ $# -lt 1 ]
 then
@@ -48,8 +57,8 @@ source $paramsfn
 cp $fsdir/$t1 .
 cp $fsdir/$wmparc .
 
-mgzto4dfp $t1
-mgzto4dfp $wmparc
+mgzto4dfp $t1 || die "$program ERROR: mgzto4dfp $t1 failed"
+mgzto4dfp $wmparc || die "$program ERROR: mgzto4dfp $wmparc failed"
 
 mrroot=${t1%.*}
 mrroot=${mrroot}001
@@ -58,10 +67,10 @@ fsfroot=${fsfroot}001
 
 ###############################################################################
 # Processing freesurfer rois, whole head roi, and prepare for roi analysis
-if [ ! -e ${mrroot}"_g9.4dfp.img" ] 
+if [ ! -e ${mrroot}"_g9.4dfp.img" ]
 then
-	gauss_4dfp ${mrroot} 0.9
+	gauss_4dfp ${mrroot} 0.9 || die "$program ERROR: gauss_4dfp ${mrroot} 0.9 failed"
 fi
-maskimg_4dfp -v1 -t15 T1001_g9  T1001_g9 Head_Mask
-PreprocessRSFtest2 $fsfroot Head_Mask  RSFMask ROIlist.txt $fslut
+maskimg_4dfp -v1 -t15 T1001_g9  T1001_g9 Head_Mask || die "$program ERROR: maskimg_4dfp -v1 -t15 T1001_g9  T1001_g9 Head_Mask failed"
+PreprocessRSFtest2 $fsfroot Head_Mask  RSFMask ROIlist.txt $fslut || die "$program ERROR: PreprocessRSFtest2 $fsfroot Head_Mask  RSFMask ROIlist.txt $fslut failed"
 
diff --git a/scripts/reg2img b/scripts/reg2img
--- a/scripts/reg2img
+++ b/scripts/reg2img
@@ -1,12 +1,24 @@
 #!/bin/bash
 ################################################################################
-# This program registers two 4dfp images using imgreg_4dfp		       #     
+# This program registers two 4dfp images using imgreg_4dfp		       #
 ################################################################################
-# Yi Su, 2012/03/16                                                            
+# Yi Su, 2012/03/16
+VERSION=1.1
 
-idstr='$Id: reg2img,v 1.1 Fri Jan 31 09:45:13 CST 2014 suy $'
-echo $idstr
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
+
+die(){
+    echo >&2 "$@"
+    exit -1
+}
+
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Fri Jan 31 09:45:13 CST 2014 suy $'
+echo $idstr
+
 if [ $# -lt 2 ]
 then
 	echo "Usage: $program refimg movimg"
@@ -23,7 +35,7 @@ then
 	echo "	-f (only fine search is performed (default is with coarse"
 	echo "	    search))"
 	exit -1
-fi	
+fi
 
 ################################
 # setting default parameters
@@ -66,12 +78,13 @@ while [ $# -gt 0 ]; do
 	    rmsk=$2
 	    shift
 	    if [ ! -f $rmsk ]; then
-	       echo "Error: Mask file doesn't exist!"
-	       exit -1
+         ERR="$program ERROR: Mask file doesn't exist!"
+	       echo $ERR
+	       die $ERR
 	    fi
 	    grm=0
 	    ;;
-	esac   	       
+	esac
       fi
       ;;
     -rb)
@@ -79,48 +92,53 @@ while [ $# -gt 0 ]; do
        then
          case "$2" in
 	   -*)
-	     echo "Error: -rb must be followed with a number"
-	     exit -1
+	     ERR="$program ERROR: -rb must be followed with a number"
+       echo $ERR
+	     die $ERR
 	     ;;
 	   [0-9]*)
 	     rb=$2
 	     shift
 	     ;;
-	   *)     
-	     echo "Error: -rb must be followed with a number"
-	     exit -1
+	   *)
+       ERR="$program ERROR: -rb must be followed with a number"
+       echo $ERR
+       die $ERR
 	     ;;
-	 esac  
+	 esac
        fi
        ;;
-     -mb)   
+     -mb)
        if [ -n "$2" ]
        then
          case "$2" in
 	   -*)
-	     echo "Error: -mb must be followed with a number"
-	     exit -1
+       ERR="$program ERROR: -mb must be followed with a number"
+       echo $ERR
+       die $ERR
 	     ;;
 	   [0-9]*)
 	     mb=$2
 	     shift
 	     ;;
-	   *)     
-	     echo "Error: -mb must be followed with a number"
-	     exit -1
+	   *)
+       ERR="$program ERROR: -mb must be followed with a number"
+       echo $ERR
+       die $ERR
 	     ;;
-	 esac  
+	 esac
        fi
        ;;
      -*)
-      echo "Unrecognized options for reg2img"
-      exit -1
-      ;;  
+      ERR="$program ERROR: Unrecognized options"
+      echo $ERR
+      die $ERR
+      ;;
      *)
       refimg=$1
       movimg=$2
       shift
-      ;;  
+      ;;
   esac
   shift
 done
@@ -131,17 +149,19 @@ then
     refname=`basename $refimg`
     refroot=${refname%%.*}
 else
-    echo "$program: Missing refimg"
-    exit -1
-fi        
+    ERR="$program ERROR: Missing refimg"
+    echo $ERR
+    die $ERR
+fi
 if [ -n "$movimg" ]
 then
     movdir=`dirname $movimg`
     movname=`basename $movimg`
     movroot=${movname%%.*}
 else
-    echo "$program: Missing movimg"
-    exit -1
+    ERR="$program ERROR: Missing movimg"
+    echo $ERR
+    die $ERR
 fi
 
 echo refroot: $refroot
@@ -151,36 +171,36 @@ echo mb=$mb
 echo rm=$rm
 echo mm=$mm
 
-imgblur_4dfp $refimg $rb
-imgblur_4dfp $movimg $mb
+imgblur_4dfp $refimg $rb || die "$program ERROR: imgblur_4dfp $refimg $rb failed"
+imgblur_4dfp $movimg $mb || die "$program ERROR: imgblur_4dfp $movimg $mb failed"
 rbx=`echo $rb | awk '{print 10*$1}'`
 mbx=`echo $mb | awk '{print 10*$1}'`
 
 if [ "$rm" -eq 1 ] && [ "$grm" -eq 1 ]
 then
-    maskimg_4dfp ${refroot}"_b"${rbx} ${refroot}"_b"${rbx} -t.5 ${refroot}"_msk" -v1
+    maskimg_4dfp ${refroot}"_b"${rbx} ${refroot}"_b"${rbx} -t.5 ${refroot}"_msk" -v1 || die "$program ERROR: maskimg_4dfp ${refroot}_b${rbx} ${refroot}_b${rbx} -t.5 ${refroot}_msk -v1 failed"
     nsl=`gawk '/matrix size \[3\]/ {print $NF}' ${refroot}".4dfp.ifh"`
     msl=3
-    zero_slice_4dfp ${refroot}"_msk" z 1 $msl  ${refroot}"_mskz"
+    zero_slice_4dfp ${refroot}"_msk" z 1 $msl  ${refroot}"_mskz" || die "$program ERROR: zero_slice_4dfp ${refroot}_msk z 1 $msl  ${refroot}_mskz failed"
     k=$((nsl-msl+1))
-    zero_slice_4dfp ${refroot}"_mskz" z $k $nsl ${refroot}"_msk"
+    zero_slice_4dfp ${refroot}"_mskz" z $k $nsl ${refroot}"_msk" || die "$program ERROR: zero_slice_4dfp ${refroot}_mskz z $k $nsl ${refroot}_msk failed"
     rmsk=${refroot}"_msk"
 fi
 
 if [ "$mm" -eq 1 ]
 then
-    maskimg_4dfp ${movroot}"_b"${mbx} ${movroot}"_b"${mbx} -t.5 ${movroot}"_msk" -v1
+    maskimg_4dfp ${movroot}"_b"${mbx} ${movroot}"_b"${mbx} -t.5 ${movroot}"_msk" -v1 || die "$program ERROR: maskimg_4dfp ${movroot}_b${mbx} ${movroot}_b${mbx} -t.5 ${movroot}_msk -v1 failed"
     nsl=`gawk '/matrix size \[3\]/ {print $NF}' ${movroot}".4dfp.ifh"`
     msl=3
-    zero_slice_4dfp ${movroot}"_msk" z 1 $msl  ${movroot}"_mskz"
+    zero_slice_4dfp ${movroot}"_msk" z 1 $msl  ${movroot}"_mskz" || die "$program ERROR: zero_slice_4dfp ${movroot}_msk z 1 $msl  ${movroot}_mskz failed"
     k=$((nsl-msl+1))
-    zero_slice_4dfp ${movroot}"_mskz" z $k $nsl ${movroot}"_msk"
+    zero_slice_4dfp ${movroot}"_mskz" z $k $nsl ${movroot}"_msk" || die "$program ERROR: zero_slice_4dfp ${movroot}_mskz z $k $nsl ${movroot}_msk failed"
     mmsk=${movroot}"_msk"
 fi
 
 echo rmsk=$rmsk
 echo mmsk=$mmsk
- 
+
 if [ "$cross" -eq 1 ] && [ "$global" -eq 1 ]
 then
     modes=( 4099 2051 10243 )
@@ -216,21 +236,21 @@ if [ ! -e $t4file1 ]
 then
 	ori=`awk '/orientation/{print $NF - 1}' ${refdir}/${refroot}".4dfp.ifh"`
 	ori=$((ori-1))
-	t4_inv ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4"
+	t4_inv ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4"  || die "$program ERROR: t4_inv failed"
 	ori=`awk '/orientation/{print $NF - 1}' ${movdir}/${movroot}".4dfp.ifh"`
 	ori=$((ori-1))
-	t4_mul ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" $t4file1
-	rm temp$$_t4			
+	t4_mul ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" $t4file1 || die "$program ERROR: t4_mul failed"
+	rm temp$$_t4
 fi
 if [ ! -e $t4file2 ]
 then
 	ori=`awk '/orientation/{print $NF - 1}' ${movdir}/${movroot}".4dfp.ifh"`
 	ori=$((ori-1))
-	t4_inv ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4"
+	t4_inv ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" || die "$program ERROR: t4_inv failed"
 	ori=`awk '/orientation/{print $NF - 1}' ${refdir}/${refroot}".4dfp.ifh"`
 	ori=$((ori-1))
-	t4_mul ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" $t4file2
-	rm temp$$_t4		
+	t4_mul ${RELEASE}/${oristr[$ori]}"_t4" temp$$"_t4" $t4file2 || die "$program ERROR: t4_mul failed"
+	rm temp$$_t4
 fi
 
 refi=${refroot}"_b"$rbx
@@ -243,11 +263,11 @@ do
     echo >> $log
     echo imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode
     echo imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode >> $log
-         imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode >> $log
+         imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode >> $log || die "$program ERROR: imgreg_4dfp $refi $rmsk $movi $mmsk $t4file1 $mode failed"
     echo >> $log
     echo imgreg_4dfp $movi $mmsk $refi $rmsk $t4file2 $mode
     echo imgreg_4dfp $movi $mmsk $refi $rmsk $t4file2 $mode >> $log
-         imgreg_4dfp $movi $mmsk $refi $rmsk $t4file2 $mode >> $log    
+         imgreg_4dfp $movi $mmsk $refi $rmsk $t4file2 $mode >> $log || die "$program ERROR: imgreg_4dfp $movi $mmsk $refi $rmsk $t4file2 $mode failed"
 done
 
 ##################################################################################################
@@ -255,17 +275,17 @@ done
 
 resolvelog=${refroot}"_"${movroot}"_"${program}"_resolve.log"
 echo t4_resolve ${refroot} ${movroot} -o${refroot}
-t4_resolve ${refroot} ${movroot} -o${refroot} > $resolvelog
+t4_resolve ${refroot} ${movroot} -o${refroot} > $resolvelog || die "$program ERROR: t4_resolve ${refroot} ${movroot} -o${refroot} failed"
 
 error=`gawk '/estimate total rotation error/{rot = $5} /estimate total translation error/{trans = $5} END{printf ("%3d", 100*(trans + 1.4*rot))}' $resolvelog`
 echo                           >> $resolvelog
 echo "ERROR = " $error
 echo "ERROR = " $error >> $resolvelog
-if (( $error < 100 )) 
+if (( $error < 100 ))
 then
 	echo "ERROR is LOW, image reconciliation is good"
 	echo "ERROR is LOW, image reconciliation is good"             >> $resolvelog
-elif (( $error > 200 )) 
+elif (( $error > 200 ))
 then
 	echo "ERROR is HIGH, cross-image reconciliation is poor"
 	echo "ERROR is HIGH, cross-image reconciliation is poor"      >> $resolvelog
diff --git a/scripts/sif_4dfp b/scripts/sif_4dfp
--- a/scripts/sif_4dfp
+++ b/scripts/sif_4dfp
@@ -2,12 +2,23 @@
 ###############################################################################
 # Program to convert Siemens interfile data into 4dfp format data             #
 ###############################################################################
-
 # Yi Su, 2013/10/11
+VERSION=1.0
 
-idstr='$Id: sif_4dfp,v sif_4dfp Tue Feb 25 11:27:39 CST 2014 suy $'
-echo $idstr
+if [ "$1" == "--version" ]; then
+    echo $VERSION
+    exit 0
+fi
+
+die(){
+    echo >&2 "$@"
+    exit -1
+}
+
 program=`basename $0`
+idstr='$Id: '$program',v '$VERSION' Tue Feb 25 11:27:39 CST 2014 suy $'
+echo $idstr
+
 if [ $# -lt 2 ]
 then
 	echo "Usage: $program sifstr outroot"
@@ -70,9 +81,9 @@ echo "scaling factor (mm/pixel) [2]	:= $sf2" >> $tmpfr
 echo "scaling factor (mm/pixel) [3]	:= $sf3" >> $tmpfr
 
 # create 4dfp for first frame
-ifh2hdr ${tmproot}
+ifh2hdr ${tmproot} || die "$program ERROR: ifh2hdr ${tmproot} failed"
 ln -s ${sifdir}/${datafn} ${tmproot}.4dfp.img
-flip_4dfp -z ${tmproot} ${outroot}_f1
+flip_4dfp -z ${tmproot} ${outroot}_f1 || die "$program ERROR: flip_4dfp -z ${tmproot} ${outroot}_f1 failed"
 rm ${tmproot}.4dfp.*
 
 # write rec file
@@ -118,22 +129,22 @@ then
 	echo "scaling factor (mm/pixel) [3]	:= $sf3" >> $tmpfr
 
 	# create 4dfp for the $ith frame
-	ifh2hdr ${tmproot}
+	ifh2hdr ${tmproot} || die "$program ERROR: ifh2hdr ${tmproot} failed"
 	ln -s ${sifdir}/${datafn} ${tmproot}.4dfp.img
-	flip_4dfp -z ${tmproot} ${outroot}_f${i}
+	flip_4dfp -z ${tmproot} ${outroot}_f${i} || die "$program ERROR: flip_4dfp -z ${tmproot} ${outroot}_f${i} failed"
 	rm ${tmproot}.4dfp.*
 
-	# write info file	
+	# write info file
 	frd1=$(echo "scale=6; $frd*1000" | bc )
 	st1=$(echo "scale=6; $st*1000" | bc )
 	imax=`imgmax_4dfp ${outroot}_f${i} | gawk '{print $1}'`
 	imin=`imgmax_4dfp -m ${outroot}_f${i} | gawk '{print $2}'`
 	printf 'Frame_%d \t%10.0f \t%10.2f \t%10.0f \t%10.2f \t%10.2f \t%10.6f \t%10s\n' $i $frd1 $t $st1 $imin $imax $dcf 1 >>${outroot}1.4dfp.img.rec
-	
+
 	# create lst file
 	echo ${outroot}_f${i} >> ${outroot}.lst
     done
-    paste_4dfp -a ${outroot}.lst $outroot
+    paste_4dfp -a ${outroot}.lst $outroot || die "$program ERROR: paste_4dfp -a ${outroot}.lst $outroot failed"
     rm ${outroot}_f*.4dfp.*
     rm ${outroot}.lst
 else
@@ -143,7 +154,7 @@ fi
 instr=`grep "conversion program" ${outroot}.4dfp.ifh`
 outstr="conversion program	:= sif_4dfp"
 sed "s/$instr/$outstr/" -i ${outroot}.4dfp.ifh
-ifh2hdr ${outroot}
+ifh2hdr ${outroot} || die "$program ERROR: ifh2hdr ${outroot} failed"
 rm ${outroot}.4dfp.img.rec
 cp ${outroot}1.4dfp.img.rec ${outroot}.4dfp.img.rec
 echo endrec `date` `whoami` >> ${outroot}.4dfp.img.rec
